name: makemylist
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  sqflite: ^2.4.1
  meta: ^1.15.0
  lucide_icons: ^0.257.0
  gap: ^3.0.1
  flutter_gen: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto_Condensed-BlackItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-Black.ttf
        - asset: assets/fonts/Roboto_Condensed-BoldItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf
        - asset: assets/fonts/Roboto_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-ExtraBold.ttf
        - asset: assets/fonts/Roboto_Condensed-ExtraLightItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-ExtraLight.ttf
        - asset: assets/fonts/Roboto_Condensed-Italic.ttf
        - asset: assets/fonts/Roboto_Condensed-LightItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto_Condensed-MediumItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf
        - asset: assets/fonts/Roboto_Condensed-ThinItalic.ttf
        - asset: assets/fonts/Roboto_Condensed-Thin.ttf
        - asset: assets/fonts/Roboto-ExtraBoldItalic.ttf
        - asset: assets/fonts/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto-ExtraLightItalic.ttf
        - asset: assets/fonts/Roboto-ExtraLight.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-SemiBoldItalic.ttf
        - asset: assets/fonts/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-BlackItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Black.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-ExtraLight.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Italic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Light.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Medium.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Regular.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-ThinItalic.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
